```{r}
studentID
str_sub(studentID,5,6)
str_sub(studentID,2,4)
```
```{r}
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```
```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```
```{r}
month
day
str_c(month,day, sep="-")
```
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("https://github.com",username,reponame, sep="/")
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```
```{r}
y <- str_sub(birthday,1,4)
m <- str_sub(birthday,5,6)
d <- str_sub(birthday,7,8)
birday <- str_c("西元",y,"年",m,"月",d,"日")
birday
```

```{r}
民國年月<-c("099/01","099/02","099/03")
a <- str_sub(民國年月,2,3)
a
b <- str_sub(民國年月,4,6)
b
c <- as.integer(a)+1911
c
西元年月<- str_c(c,b)
西元年月
```















